
---
- name: Install Hashicorp vault playbook
  hosts: "{{ hosts }}"
  become: yes
  vars: 
#    _src_iptables: "iptables/rules.v4"
#    _src_ipset: "ipset/ipset.rules"
  roles:
    #- { role: default-setting-debian-11, when: ansible_system == 'Linux' and ansible_distribution == 'Debian' and ansible_distribution_major_version == '11' }
    #- { role: setting-firewall, when: ansible_system == 'Linux' }
    #- { role: zabbix-agent2-debian-11, when: ansible_system == 'Linux' and ansible_distribution == 'Debian' and ansible_distribution_major_version == '11' }
    #- { role: setting-ssh, when: ansible_system == 'Linux' }
    #- { role: docker-install-debian, when: ansible_system == 'Linux' }
    - { role: install-vault-debian, when: ansible_system == 'Linux' and ansible_distribution == 'Debian' }
