---
- name: Vault Config | Getting name of init server 
  set_fact:
    hostname_init_server: "{{ inventory_hostname }}"
  when: role == 'init'
  delegate_facts: true
  delegate_to: localhost

- name: Vault Config | Getting name of master server 
  set_fact:
    hostname_master_server: "{{ inventory_hostname }}"
  when: role == 'master'
  delegate_facts: true
  delegate_to: localhost


- name: Vault Config | Copying script for configuration
  vars:
    hostname_init_server: "{{ hostvars['localhost'].hostname_init_server }}"
    hostname_master_server: "{{ hostvars['localhost'].hostname_master_server }}"
  template:
     src: cluster.sh 
     dest: "{{ vault_dir }}/cluster.sh"
     mode: 755


- name: Vault Config | Copying configuration file for init server
  template:
     src: config-init.hcl
     dest: "{{ vault_dir }}/config-init.hcl"
     mode: 644
  when: role == 'init'

- name: Vault Config | Copying configuration file for master server
  vars:
    hostname_init_server: "{{ hostvars['localhost'].hostname_init_server }}"
  template:
     src: config-worker.hcl
     dest: "{{ vault_dir }}/config-master.hcl"
     mode: 644
  when: role == 'master'

- name: Vault Config | Copying configuration file for worker server
  vars:
    hostname_init_server: "{{ hostvars['localhost'].hostname_init_server }}"
  template:
     src: config-worker.hcl
     dest: "{{ vault_dir }}/config-worker.hcl"
     mode: 644
  when: role == 'worker'


